FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive

ARG UID
ARG GID

RUN apt update && apt install -y wget git build-essential python3 libpython3-dev python3-venv curl && \
    groupadd -g $GID ubuntu && useradd -m -u $UID -g $GID ubuntu -s /usr/bin/bash

USER ubuntu

SHELL ["/bin/bash", "-c"]

RUN cd ~ && \
    curl -sSL https://install.python-poetry.org | python3 - && \
    echo 'export PATH="/home/ubuntu/.local/bin:$PATH"' >> ~/.bashrc && \
    export PATH="/home/ubuntu/.local/bin:$PATH" && \
    poetry completions bash >> ~/.bash_completion

WORKDIR /home/ubuntu/

ENTRYPOINT ["/bin/bash"]
